#!/bin/bash

# Environment Setup Script for CheckjeBon Import
# ==============================================
# This script helps set up environment variables and configuration

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_DIR/.env"
ENV_EXAMPLE="$PROJECT_DIR/.env.example"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Utility functions
log_info() {
    echo -e "${BLUE}INFO${NC}: $1"
}

log_success() {
    echo -e "${GREEN}SUCCESS${NC}: $1"
}

log_error() {
    echo -e "${RED}ERROR${NC}: $1"
}

log_warning() {
    echo -e "${YELLOW}WARNING${NC}: $1"
}

# Create .env.example file
create_env_example() {
    cat > "$ENV_EXAMPLE" << 'EOF'
# CheckjeBon Import Environment Variables
# ======================================
# Copy this file to .env and fill in your values

# Supabase Configuration (Required)
SUPABASE_URL=https://your-project-id.supabase.co
SUPABASE_KEY=your-supabase-anon-key

# Email Notifications (Optional)
EMAIL_ENABLED=false
EMAIL_TO=admin@example.com
EMAIL_FROM=noreply@checkjebon.local
EMAIL_SMTP_HOST=smtp.gmail.com
EMAIL_SMTP_PORT=587
EMAIL_SMTP_USER=your-email@gmail.com
EMAIL_SMTP_PASSWORD=your-app-password

# Import Configuration (Optional)
IMPORT_BATCH_SIZE=50
IMPORT_TIMEOUT=1800
LOG_LEVEL=INFO
LOG_RETENTION_DAYS=30

# System Configuration (Optional)
PYTHONPATH=/path/to/boodschappen_app
PYTHON_ENV=production
TZ=Europe/Amsterdam

# Database Configuration (Optional)
DB_CONNECTION_TIMEOUT=30
DB_MAX_RETRIES=3
DB_RETRY_DELAY=5

# Monitoring Configuration (Optional)
MONITORING_ENABLED=true
HEALTH_CHECK_INTERVAL=3600
METRICS_RETENTION_DAYS=90

# Webhook Configuration (Optional)
WEBHOOK_ENABLED=false
WEBHOOK_URL=https://your-webhook-endpoint.com
WEBHOOK_SECRET=your-webhook-secret
EOF
    
    log_info "Created example environment file: $ENV_EXAMPLE"
}

# Interactive setup
interactive_setup() {
    log_info "Interactive environment setup"
    echo "=============================="
    
    # Create .env file
    cat > "$ENV_FILE" << 'EOF'
# CheckjeBon Import Environment Variables
# ======================================
# Generated by setup script

EOF
    
    # Get Supabase configuration
    echo ""
    echo -e "${BLUE}Supabase Configuration${NC}"
    echo "----------------------"
    
    read -p "Enter your Supabase URL: " supabase_url
    while [[ ! "$supabase_url" =~ ^https://.*\.supabase\.co$ ]]; do
        echo -e "${RED}Invalid URL format. Should be like: https://project-id.supabase.co${NC}"
        read -p "Enter your Supabase URL: " supabase_url
    done
    
    read -s -p "Enter your Supabase anon key: " supabase_key
    echo ""
    
    # Validate key format (basic check)
    if [[ ! "$supabase_key" =~ ^eyJ ]]; then
        log_warning "Key doesn't appear to be in JWT format, but continuing..."
    fi
    
    # Write Supabase config
    echo "SUPABASE_URL=$supabase_url" >> "$ENV_FILE"
    echo "SUPABASE_KEY=$supabase_key" >> "$ENV_FILE"
    echo "" >> "$ENV_FILE"
    
    # Email configuration
    echo ""
    echo -e "${BLUE}Email Notifications${NC}"
    echo "-------------------"
    
    read -p "Enable email notifications? (y/n): " enable_email
    if [[ "$enable_email" =~ ^[Yy]$ ]]; then
        echo "EMAIL_ENABLED=true" >> "$ENV_FILE"
        
        read -p "Enter notification email address: " email_to
        echo "EMAIL_TO=$email_to" >> "$ENV_FILE"
        
        read -p "Enter sender email address: " email_from
        echo "EMAIL_FROM=$email_from" >> "$ENV_FILE"
        
        read -p "Enter SMTP host (default: smtp.gmail.com): " smtp_host
        smtp_host=${smtp_host:-smtp.gmail.com}
        echo "EMAIL_SMTP_HOST=$smtp_host" >> "$ENV_FILE"
        
        read -p "Enter SMTP port (default: 587): " smtp_port
        smtp_port=${smtp_port:-587}
        echo "EMAIL_SMTP_PORT=$smtp_port" >> "$ENV_FILE"
        
        read -p "Enter SMTP username: " smtp_user
        echo "EMAIL_SMTP_USER=$smtp_user" >> "$ENV_FILE"
        
        read -s -p "Enter SMTP password: " smtp_password
        echo ""
        echo "EMAIL_SMTP_PASSWORD=$smtp_password" >> "$ENV_FILE"
    else
        echo "EMAIL_ENABLED=false" >> "$ENV_FILE"
    fi
    
    echo "" >> "$ENV_FILE"
    
    # Import configuration
    echo ""
    echo -e "${BLUE}Import Configuration${NC}"
    echo "--------------------"
    
    read -p "Enter batch size (default: 50): " batch_size
    batch_size=${batch_size:-50}
    echo "IMPORT_BATCH_SIZE=$batch_size" >> "$ENV_FILE"
    
    read -p "Enter log level (INFO/DEBUG/WARNING/ERROR) [default: INFO]: " log_level
    log_level=${log_level:-INFO}
    echo "LOG_LEVEL=$log_level" >> "$ENV_FILE"
    
    read -p "Enter log retention days (default: 30): " retention_days
    retention_days=${retention_days:-30}
    echo "LOG_RETENTION_DAYS=$retention_days" >> "$ENV_FILE"
    
    # System configuration
    echo "" >> "$ENV_FILE"
    echo "# System Configuration" >> "$ENV_FILE"
    echo "PYTHONPATH=$PROJECT_DIR" >> "$ENV_FILE"
    echo "PYTHON_ENV=production" >> "$ENV_FILE"
    echo "TZ=Europe/Amsterdam" >> "$ENV_FILE"
    
    log_success "Environment file created: $ENV_FILE"
}

# Validate environment
validate_environment() {
    log_info "Validating environment configuration..."
    
    if [ ! -f "$ENV_FILE" ]; then
        log_error "Environment file not found: $ENV_FILE"
        return 1
    fi
    
    # Source the environment file
    source "$ENV_FILE"
    
    # Check required variables
    local errors=0
    
    if [ -z "$SUPABASE_URL" ]; then
        log_error "SUPABASE_URL is not set"
        errors=$((errors + 1))
    elif [[ ! "$SUPABASE_URL" =~ ^https://.*\.supabase\.co$ ]]; then
        log_error "SUPABASE_URL format is invalid"
        errors=$((errors + 1))
    fi
    
    if [ -z "$SUPABASE_KEY" ]; then
        log_error "SUPABASE_KEY is not set"
        errors=$((errors + 1))
    elif [[ ! "$SUPABASE_KEY" =~ ^eyJ ]]; then
        log_warning "SUPABASE_KEY doesn't appear to be in JWT format"
    fi
    
    # Check optional email configuration
    if [ "$EMAIL_ENABLED" = "true" ]; then
        if [ -z "$EMAIL_TO" ]; then
            log_error "EMAIL_TO is not set but EMAIL_ENABLED is true"
            errors=$((errors + 1))
        fi
        
        if [ -z "$EMAIL_FROM" ]; then
            log_error "EMAIL_FROM is not set but EMAIL_ENABLED is true"
            errors=$((errors + 1))
        fi
    fi
    
    # Check numeric values
    if [ -n "$IMPORT_BATCH_SIZE" ] && ! [[ "$IMPORT_BATCH_SIZE" =~ ^[0-9]+$ ]]; then
        log_error "IMPORT_BATCH_SIZE must be a number"
        errors=$((errors + 1))
    fi
    
    if [ -n "$LOG_RETENTION_DAYS" ] && ! [[ "$LOG_RETENTION_DAYS" =~ ^[0-9]+$ ]]; then
        log_error "LOG_RETENTION_DAYS must be a number"
        errors=$((errors + 1))
    fi
    
    if [ $errors -eq 0 ]; then
        log_success "Environment validation passed"
        return 0
    else
        log_error "Environment validation failed with $errors errors"
        return 1
    fi
}

# Test database connection
test_connection() {
    log_info "Testing database connection..."
    
    if [ ! -f "$ENV_FILE" ]; then
        log_error "Environment file not found. Run setup first."
        return 1
    fi
    
    # Source environment
    source "$ENV_FILE"
    
    # Set up Python environment
    if [ -f "$PROJECT_DIR/venv/bin/activate" ]; then
        source "$PROJECT_DIR/venv/bin/activate"
    else
        log_error "Python virtual environment not found. Run setup first."
        return 1
    fi
    
    # Test connection using the import script
    cd "$PROJECT_DIR"
    python supabase_import.py --dry-run --batch-size=1 > /dev/null 2>&1
    local exit_code=$?
    
    if [ $exit_code -eq 0 ]; then
        log_success "Database connection test passed"
        return 0
    else
        log_error "Database connection test failed"
        return 1
    fi
}

# Show current environment
show_environment() {
    log_info "Current environment configuration:"
    
    if [ ! -f "$ENV_FILE" ]; then
        log_error "Environment file not found: $ENV_FILE"
        return 1
    fi
    
    echo ""
    echo "File: $ENV_FILE"
    echo "=================="
    
    # Show file contents with sensitive values masked
    while IFS= read -r line; do
        if [[ "$line" =~ ^[[:space:]]*# ]] || [[ -z "$line" ]]; then
            echo "$line"
        elif [[ "$line" =~ = ]]; then
            key=$(echo "$line" | cut -d= -f1)
            value=$(echo "$line" | cut -d= -f2-)
            
            # Mask sensitive values
            if [[ "$key" =~ (KEY|PASSWORD|SECRET|TOKEN) ]]; then
                echo "$key=***MASKED***"
            else
                echo "$line"
            fi
        else
            echo "$line"
        fi
    done < "$ENV_FILE"
}

# Create systemd environment file
create_systemd_env() {
    local systemd_env_file="$PROJECT_DIR/automation/checkjebon-import.env"
    
    log_info "Creating systemd environment file..."
    
    if [ ! -f "$ENV_FILE" ]; then
        log_error "Environment file not found. Run setup first."
        return 1
    fi
    
    # Copy .env file but remove comments and empty lines
    grep -v '^#' "$ENV_FILE" | grep -v '^$' > "$systemd_env_file"
    
    log_info "Created systemd environment file: $systemd_env_file"
    log_info "This file can be used with systemd services"
}

# Backup environment
backup_environment() {
    if [ -f "$ENV_FILE" ]; then
        local backup_file="${ENV_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
        cp "$ENV_FILE" "$backup_file"
        log_success "Environment backed up to: $backup_file"
    else
        log_warning "No environment file to backup"
    fi
}

# Main function
main() {
    echo -e "${BLUE}CheckjeBon Environment Setup${NC}"
    echo "============================"
    
    case "${1:-}" in
        setup)
            create_env_example
            interactive_setup
            validate_environment
            ;;
        validate)
            validate_environment
            ;;
        test)
            test_connection
            ;;
        show)
            show_environment
            ;;
        systemd)
            create_systemd_env
            ;;
        backup)
            backup_environment
            ;;
        example)
            create_env_example
            log_success "Example environment file created: $ENV_EXAMPLE"
            ;;
        *)
            echo "Usage: $0 {setup|validate|test|show|systemd|backup|example}"
            echo ""
            echo "Commands:"
            echo "  setup    - Interactive environment setup"
            echo "  validate - Validate current environment"
            echo "  test     - Test database connection"
            echo "  show     - Show current environment (masked)"
            echo "  systemd  - Create systemd environment file"
            echo "  backup   - Backup current environment"
            echo "  example  - Create example environment file"
            echo ""
            exit 1
            ;;
    esac
}

main "$@"